"""add historical policies for rag

Revision ID: 30df002f6c80
Revises: fa36871be79e
Create Date: 2026-04-26 15:42:06.668066

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "30df002f6c80"  # pragma: allowlist secret
down_revision: str | None = "fa36871be79e"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_policies",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("policy_number", sa.String(length=60), nullable=False),
        sa.Column("insured_name", sa.String(length=200), nullable=False),
        sa.Column("business_description", sa.Text(), nullable=False),
        sa.Column("fleet_size", sa.Integer(), nullable=False),
        sa.Column("primary_vehicle_type", sa.String(length=40), nullable=False),
        sa.Column("annual_revenue", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("operates_internationally", sa.Boolean(), nullable=False),
        sa.Column("claims_count_5y", sa.Integer(), nullable=False),
        sa.Column("claims_value_5y", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("risk_band", sa.String(length=10), nullable=False),
        sa.Column("final_premium", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("bound", sa.Boolean(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("actual_claims_count", sa.Integer(), nullable=False),
        sa.Column("actual_claims_value", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("loss_ratio", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("underwriter_notes", sa.Text(), nullable=False),
        sa.Column("embedding_text", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_policies")),
    )
    op.create_index(
        op.f("ix_historical_policies_policy_number"),
        "historical_policies",
        ["policy_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_historical_policies_policy_number"), table_name="historical_policies")
    op.drop_table("historical_policies")
    # ### end Alembic commands ###
