"""create initial schema

Revision ID: dd8d4ef14dc0
Revises:
Create Date: 2026-04-25 23:58:36.273917

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "dd8d4ef14dc0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submissions",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("reference", sa.String(length=50), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("insured_name", sa.String(length=200), nullable=False),
        sa.Column("insured_address", sa.JSON(), nullable=False),
        sa.Column("business_description", sa.Text(), nullable=False),
        sa.Column("annual_revenue_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("annual_revenue_currency", sa.String(length=3), nullable=False),
        sa.Column("vehicles", sa.JSON(), nullable=False),
        sa.Column("drivers", sa.JSON(), nullable=False),
        sa.Column("operates_internationally", sa.Boolean(), nullable=False),
        sa.Column("countries_of_operation", sa.JSON(), nullable=False),
        sa.Column("claims_count_5y", sa.Integer(), nullable=False),
        sa.Column("claims_value_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("claims_value_currency", sa.String(length=3), nullable=False),
        sa.Column("coverage_type", sa.String(length=30), nullable=False),
        sa.Column("coverage_start", sa.Date(), nullable=False),
        sa.Column("coverage_end", sa.Date(), nullable=False),
        sa.Column("coverage_excess_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("coverage_excess_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
    )
    op.create_index(op.f("ix_submissions_reference"), "submissions", ["reference"], unique=True)
    op.create_index(op.f("ix_submissions_status"), "submissions", ["status"], unique=False)
    op.create_table(
        "quotes",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("submission_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("quote_reference", sa.String(length=50), nullable=False),
        sa.Column("premium_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("premium_currency", sa.String(length=3), nullable=False),
        sa.Column("excess_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("excess_currency", sa.String(length=3), nullable=False),
        sa.Column("coverage_type", sa.String(length=30), nullable=False),
        sa.Column("coverage_start", sa.Date(), nullable=False),
        sa.Column("coverage_end", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], name=op.f("fk_quotes_submission_id_submissions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
    )
    op.create_index(op.f("ix_quotes_quote_reference"), "quotes", ["quote_reference"], unique=True)
    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("risk_band", sa.String(length=10), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_risk_assessments_submission_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_assessments")),
    )
    op.create_index(
        op.f("ix_risk_assessments_risk_band"), "risk_assessments", ["risk_band"], unique=False
    )
    op.create_table(
        "triage_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("appetite_matches", sa.JSON(), nullable=False),
        sa.Column("appetite_concerns", sa.JSON(), nullable=False),
        sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_triage_results_submission_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_triage_results")),
    )
    op.create_index(
        op.f("ix_triage_results_decision"), "triage_results", ["decision"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("policy_number", sa.String(length=50), nullable=False),
        sa.Column("quote_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("submission_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("insured_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("premium_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("premium_currency", sa.String(length=3), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bound_by", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["quotes.id"], name=op.f("fk_policies_quote_id_quotes")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_policies_submission_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
    )
    op.create_index(op.f("ix_policies_policy_number"), "policies", ["policy_number"], unique=True)
    op.create_index(op.f("ix_policies_status"), "policies", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policies_status"), table_name="policies")
    op.drop_index(op.f("ix_policies_policy_number"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_triage_results_decision"), table_name="triage_results")
    op.drop_table("triage_results")
    op.drop_index(op.f("ix_risk_assessments_risk_band"), table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.drop_index(op.f("ix_quotes_quote_reference"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_submissions_status"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_reference"), table_name="submissions")
    op.drop_table("submissions")
    # ### end Alembic commands ###
