"""add endorsements table

Revision ID: fa36871be79e
Revises: dd8d4ef14dc0
Create Date: 2026-04-26 13:02:52.293427

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fa36871be79e"  # pragma: allowlist secret
down_revision: str | None = "dd8d4ef14dc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endorsements",
        sa.Column("id", mysql.CHAR(length=36), nullable=False),
        sa.Column("policy_id", mysql.CHAR(length=36), nullable=False),
        sa.Column("endorsement_number", sa.String(length=60), nullable=False),
        sa.Column("endorsement_type", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("premium_adjustment_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("premium_adjustment_currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["policies.id"], name=op.f("fk_endorsements_policy_id_policies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endorsements")),
    )
    op.create_index(
        op.f("ix_endorsements_endorsement_number"),
        "endorsements",
        ["endorsement_number"],
        unique=True,
    )
    op.create_index(op.f("ix_endorsements_policy_id"), "endorsements", ["policy_id"], unique=False)
    op.create_index(op.f("ix_endorsements_status"), "endorsements", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_endorsements_status"), table_name="endorsements")
    op.drop_index(op.f("ix_endorsements_policy_id"), table_name="endorsements")
    op.drop_index(op.f("ix_endorsements_endorsement_number"), table_name="endorsements")
    op.drop_table("endorsements")
    # ### end Alembic commands ###
